/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Transformer.Models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Address extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7147542958860594806L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Address\",\"namespace\":\"Transformer.Models\",\"fields\":[{\"name\":\"City\",\"type\":\"string\"},{\"name\":\"Lien1\",\"type\":\"string\"},{\"name\":\"Zipcode\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Address> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Address> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Address> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Address> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Address> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Address to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Address from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Address instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Address fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence City;
  private java.lang.CharSequence Lien1;
  private java.lang.CharSequence Zipcode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Address() {}

  /**
   * All-args constructor.
   * @param City The new value for City
   * @param Lien1 The new value for Lien1
   * @param Zipcode The new value for Zipcode
   */
  public Address(java.lang.CharSequence City, java.lang.CharSequence Lien1, java.lang.CharSequence Zipcode) {
    this.City = City;
    this.Lien1 = Lien1;
    this.Zipcode = Zipcode;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return City;
    case 1: return Lien1;
    case 2: return Zipcode;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: City = (java.lang.CharSequence)value$; break;
    case 1: Lien1 = (java.lang.CharSequence)value$; break;
    case 2: Zipcode = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'City' field.
   * @return The value of the 'City' field.
   */
  public java.lang.CharSequence getCity() {
    return City;
  }


  /**
   * Sets the value of the 'City' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.City = value;
  }

  /**
   * Gets the value of the 'Lien1' field.
   * @return The value of the 'Lien1' field.
   */
  public java.lang.CharSequence getLien1() {
    return Lien1;
  }


  /**
   * Sets the value of the 'Lien1' field.
   * @param value the value to set.
   */
  public void setLien1(java.lang.CharSequence value) {
    this.Lien1 = value;
  }

  /**
   * Gets the value of the 'Zipcode' field.
   * @return The value of the 'Zipcode' field.
   */
  public java.lang.CharSequence getZipcode() {
    return Zipcode;
  }


  /**
   * Sets the value of the 'Zipcode' field.
   * @param value the value to set.
   */
  public void setZipcode(java.lang.CharSequence value) {
    this.Zipcode = value;
  }

  /**
   * Creates a new Address RecordBuilder.
   * @return A new Address RecordBuilder
   */
  public static Transformer.Models.Address.Builder newBuilder() {
    return new Transformer.Models.Address.Builder();
  }

  /**
   * Creates a new Address RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Address RecordBuilder
   */
  public static Transformer.Models.Address.Builder newBuilder(Transformer.Models.Address.Builder other) {
    if (other == null) {
      return new Transformer.Models.Address.Builder();
    } else {
      return new Transformer.Models.Address.Builder(other);
    }
  }

  /**
   * Creates a new Address RecordBuilder by copying an existing Address instance.
   * @param other The existing instance to copy.
   * @return A new Address RecordBuilder
   */
  public static Transformer.Models.Address.Builder newBuilder(Transformer.Models.Address other) {
    if (other == null) {
      return new Transformer.Models.Address.Builder();
    } else {
      return new Transformer.Models.Address.Builder(other);
    }
  }

  /**
   * RecordBuilder for Address instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Address>
    implements org.apache.avro.data.RecordBuilder<Address> {

    private java.lang.CharSequence City;
    private java.lang.CharSequence Lien1;
    private java.lang.CharSequence Zipcode;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Transformer.Models.Address.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.City)) {
        this.City = data().deepCopy(fields()[0].schema(), other.City);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.Lien1)) {
        this.Lien1 = data().deepCopy(fields()[1].schema(), other.Lien1);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Zipcode)) {
        this.Zipcode = data().deepCopy(fields()[2].schema(), other.Zipcode);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Address instance
     * @param other The existing instance to copy.
     */
    private Builder(Transformer.Models.Address other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.City)) {
        this.City = data().deepCopy(fields()[0].schema(), other.City);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Lien1)) {
        this.Lien1 = data().deepCopy(fields()[1].schema(), other.Lien1);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Zipcode)) {
        this.Zipcode = data().deepCopy(fields()[2].schema(), other.Zipcode);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'City' field.
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return City;
    }


    /**
      * Sets the value of the 'City' field.
      * @param value The value of 'City'.
      * @return This builder.
      */
    public Transformer.Models.Address.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.City = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'City' field has been set.
      * @return True if the 'City' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'City' field.
      * @return This builder.
      */
    public Transformer.Models.Address.Builder clearCity() {
      City = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Lien1' field.
      * @return The value.
      */
    public java.lang.CharSequence getLien1() {
      return Lien1;
    }


    /**
      * Sets the value of the 'Lien1' field.
      * @param value The value of 'Lien1'.
      * @return This builder.
      */
    public Transformer.Models.Address.Builder setLien1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Lien1 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Lien1' field has been set.
      * @return True if the 'Lien1' field has been set, false otherwise.
      */
    public boolean hasLien1() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Lien1' field.
      * @return This builder.
      */
    public Transformer.Models.Address.Builder clearLien1() {
      Lien1 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Zipcode' field.
      * @return The value.
      */
    public java.lang.CharSequence getZipcode() {
      return Zipcode;
    }


    /**
      * Sets the value of the 'Zipcode' field.
      * @param value The value of 'Zipcode'.
      * @return This builder.
      */
    public Transformer.Models.Address.Builder setZipcode(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.Zipcode = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Zipcode' field has been set.
      * @return True if the 'Zipcode' field has been set, false otherwise.
      */
    public boolean hasZipcode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Zipcode' field.
      * @return This builder.
      */
    public Transformer.Models.Address.Builder clearZipcode() {
      Zipcode = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Address build() {
      try {
        Address record = new Address();
        record.City = fieldSetFlags()[0] ? this.City : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Lien1 = fieldSetFlags()[1] ? this.Lien1 : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.Zipcode = fieldSetFlags()[2] ? this.Zipcode : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Address>
    WRITER$ = (org.apache.avro.io.DatumWriter<Address>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Address>
    READER$ = (org.apache.avro.io.DatumReader<Address>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.City);

    out.writeString(this.Lien1);

    out.writeString(this.Zipcode);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.City = in.readString(this.City instanceof Utf8 ? (Utf8)this.City : null);

      this.Lien1 = in.readString(this.Lien1 instanceof Utf8 ? (Utf8)this.Lien1 : null);

      this.Zipcode = in.readString(this.Zipcode instanceof Utf8 ? (Utf8)this.Zipcode : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.City = in.readString(this.City instanceof Utf8 ? (Utf8)this.City : null);
          break;

        case 1:
          this.Lien1 = in.readString(this.Lien1 instanceof Utf8 ? (Utf8)this.Lien1 : null);
          break;

        case 2:
          this.Zipcode = in.readString(this.Zipcode instanceof Utf8 ? (Utf8)this.Zipcode : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










