// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Transformer.Models
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class Address : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Address\",\"namespace\":\"Transformer.Models\",\"fields\":[{\"na" +
				"me\":\"City\",\"type\":\"string\"},{\"name\":\"Lien1\",\"type\":\"string\"},{\"name\":\"Zipcode\",\"" +
				"type\":\"string\"}]}");
		private string _City;
		private string _Lien1;
		private string _Zipcode;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Address._SCHEMA;
			}
		}
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				this._City = value;
			}
		}
		public string Lien1
		{
			get
			{
				return this._Lien1;
			}
			set
			{
				this._Lien1 = value;
			}
		}
		public string Zipcode
		{
			get
			{
				return this._Zipcode;
			}
			set
			{
				this._Zipcode = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.City;
			case 1: return this.Lien1;
			case 2: return this.Zipcode;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.City = (System.String)fieldValue; break;
			case 1: this.Lien1 = (System.String)fieldValue; break;
			case 2: this.Zipcode = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
