FROM confluentinc/cp-kafka-connect:7.6.1

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.4.1
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-avro-converter:latest
